Enabling workflows in features branches

diff --git a/.github/workflows/code_cov.yml b/.github/workflows/code_cov.yml
--- a/.github/workflows/code_cov.yml
+++ b/.github/workflows/code_cov.yml
@@ -10,62 +10,53 @@ jobs:
       matrix:
         mongodb-version: ['7.0']
 
-
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
-    - name: Checkout repository
-      uses: actions/checkout@v2
+
     - name: Install Python 3.9
-      uses: actions/setup-python@v1
+      uses: actions/setup-python@v4
       with:
         python-version: 3.9
+
     - name: Install dependencies
       run: |
-        pip install pytest-cov
+        pip install pytest pytest-cov coverage
         pip install -r requirements.txt
-        echo requirements installed
-        # pip uninstall bson
-        # pip uninstall pymongo
-        # pip install pymongo
+
     - name: Cleanup MongoDB container
       run: |
         if [ "$(docker ps -aq -f name=mongodb)" ]; then
           docker rm -f mongodb || true
         fi
+
     - name: Start MongoDB
       uses: supercharge/mongodb-github-action@1.10.0
       with:
         mongodb-version: ${{ matrix.mongodb-version }}
-    - name: Run the tests
+
+    - name: Run the tests and collect coverage
       run: |
-        python application.py &
-        sleep 5
-        {
-          echo "Running tests..."
-          coverage run -m unittest tests.test_module > test_output.log 2>&1 &
-          coverage_pid=$!
+        python application.py &  # Start the application in the background
+        app_pid=$!  # Capture the application's PID
+        sleep 5  # Allow the app to initialize
 
-          sleep 60
+        echo "Running tests..."
+        coverage run -m unittest discover tests > test_output.log 2>&1
+        test_exit_code=$?  # Capture the test command's exit code
 
-          if ps -p $coverage_pid > /dev/null; then
-            kill $coverage_pid  # Terminate the background process
-            if grep -q "FAILED" test_output.log; then
-                exit_code=1        # Fail if any tests failed
-            else
-              exit_code=0
-            fi
-          else
-            wait $coverage_pid   # Wait for the process to finish and get the exit code
-            exit_code=$?        # Capture the exit code
-          fi
+        # Stop the application process
+        if ps -p $app_pid > /dev/null; then
+          kill $app_pid
+        fi
 
-          # Generate XML and report if tests finished
-          if [ $exit_code -eq 0 ]; then
-            coverage xml -i
-            coverage report -m
-          fi
+        # Display the test logs
+        cat test_output.log
 
-          cat test_output.log
-          exit $exit_code
-        }
+        # Generate coverage report if tests passed
+        if [ $test_exit_code -eq 0 ]; then
+          coverage xml -i
+          coverage report -m
+        fi
+
+        exit $test_exit_code  # Fail the job if tests failed
